Food.create(name:'うどん', category:'麺類')
Food.create(name:'そうめん', category:'麺類')
Food.create(name:'そば', category:'麺類')
Food.create(name:'パスタ', category:'麺類')
Food.create(name:'ラーメン', category:'麺類')
Food.create(name:'冷麺', category:'麺類')
Food.create(name:'焼きそば', category:'麺類')

Food.create(name:'アスパラガス', category:'野菜')
Food.create(name:'かぼちゃ', category:'野菜')
Food.create(name:'キノコ', category:'野菜')
Food.create(name:'キャベツ', category:'野菜')
Food.create(name:'ごぼう', category:'野菜')
Food.create(name:'さつまいも', category:'野菜')
Food.create(name:'さといも', category:'野菜')
Food.create(name:'じゃがいも', category:'野菜')
Food.create(name:'しょうが', category:'野菜')
Food.create(name:'だいこん', category:'野菜')
Food.create(name:'たけのこ', category:'野菜')
Food.create(name:'たまねぎ', category:'野菜')
Food.create(name:'とうもろこし', category:'野菜')
Food.create(name:'トマト', category:'野菜')
Food.create(name:'なす', category:'野菜')
Food.create(name:'にんじん', category:'野菜')
Food.create(name:'にんにく', category:'野菜')
Food.create(name:'ねぎ', category:'野菜')
Food.create(name:'ピーマン', category:'野菜')
Food.create(name:'ブロッコリー', category:'野菜')
Food.create(name:'らっきょう', category:'野菜')
Food.create(name:'レタス', category:'野菜')
Food.create(name:'れんこん', category:'野菜')
Food.create(name:'山菜', category:'野菜')
Food.create(name:'豆類', category:'野菜')
Food.create(name:'白菜', category:'野菜')

Food.create(name:'アジ', category:'水産物')
Food.create(name:'アナゴ', category:'水産物')
Food.create(name:'イカ', category:'水産物')
Food.create(name:'イクラ・筋子', category:'水産物')
Food.create(name:'イワシ', category:'水産物')
Food.create(name:'ウナギ', category:'水産物')
Food.create(name:'ウニ', category:'水産物')
Food.create(name:'エビ', category:'水産物')
Food.create(name:'カツオ', category:'水産物')
Food.create(name:'カニ', category:'水産物')
Food.create(name:'サケ', category:'水産物')
Food.create(name:'サバ', category:'水産物')
Food.create(name:'サンマ', category:'水産物')
Food.create(name:'シシャモ', category:'水産物')
Food.create(name:'タイ', category:'水産物')
Food.create(name:'タコ', category:'水産物')
Food.create(name:'タラ', category:'水産物')
Food.create(name:'たらこ', category:'水産物')
Food.create(name:'ちりめん・しらす', category:'水産物')
Food.create(name:'フグ', category:'水産物')
Food.create(name:'ホッケ', category:'水産物')
Food.create(name:'マグロ', category:'水産物')
Food.create(name:'数の子', category:'水産物')
Food.create(name:'明太子', category:'水産物')
Food.create(name:'貝', category:'水産物')
Food.create(name:'海藻類', category:'水産物')

Food.create(name:'牛ヒレ肉', category:'肉')
Food.create(name:'牛ロース肉', category:'肉')
Food.create(name:'牛かた肉', category:'肉')
Food.create(name:'牛ばら肉', category:'肉')
Food.create(name:'牛もも肉', category:'肉')
Food.create(name:'牛ひき肉', category:'肉')
Food.create(name:'豚ヒレ肉', category:'肉')
Food.create(name:'豚ロース肉', category:'肉')
Food.create(name:'豚かた肉', category:'肉')
Food.create(name:'豚ばら肉', category:'肉')
Food.create(name:'豚もも肉', category:'肉')
Food.create(name:'豚ひき肉', category:'肉')
Food.create(name:'とり手羽肉', category:'肉')
Food.create(name:'とりむね肉', category:'肉')
Food.create(name:'とりもも肉', category:'肉')
Food.create(name:'とりささみ', category:'肉')
Food.create(name:'とりかわ', category:'肉')
Food.create(name:'とりひき肉', category:'肉')
Food.create(name:'合いびき肉', category:'肉')
Food.create(name:'ベーコン', category:'肉')
Food.create(name:'ハム', category:'肉')
Food.create(name:'ソーセージ', category:'肉')

Food.create(name:'卵', category:'卵・チーズ・乳製品')
Food.create(name:'チーズ', category:'卵・チーズ・乳製品')
Food.create(name:'牛乳', category:'卵・チーズ・乳製品')
Food.create(name:'ヨーグルト', category:'卵・チーズ・乳製品')
Food.create(name:'生クリーム', category:'卵・チーズ・乳製品')

Food.create(name:'豆腐', category:'豆腐・納豆・漬物')
Food.create(name:'油揚げ・厚揚げ', category:'豆腐・納豆・漬物')
Food.create(name:'納豆', category:'豆腐・納豆・漬物')
Food.create(name:'キムチ', category:'豆腐・納豆・漬物')
Food.create(name:'梅干し', category:'豆腐・納豆・漬物')
Food.create(name:'沢庵', category:'豆腐・納豆・漬物')
Food.create(name:'漬物', category:'豆腐・納豆・漬物')
Food.create(name:'こんにゃく・白滝', category:'豆腐・納豆・漬物')
Food.create(name:'佃煮', category:'豆腐・納豆・漬物')
Food.create(name:'メンマ・ザーサイ', category:'豆腐・納豆・漬物')

Food.create(name:'みかん・オレンジ・柑橘類', category:'果物')
Food.create(name:'メロン', category:'果物')
Food.create(name:'マンゴー', category:'果物')
Food.create(name:'さくらんぼ', category:'果物')
Food.create(name:'りんご', category:'果物')
Food.create(name:'いちご', category:'果物')
Food.create(name:'パイナップル', category:'果物')
Food.create(name:'レモン', category:'果物')
Food.create(name:'グレープフルーツ', category:'果物')
Food.create(name:'キウイフルーツ', category:'果物')
Food.create(name:'ベリー類', category:'果物')
Food.create(name:'すいか', category:'果物')
Food.create(name:'梅・プラム', category:'果物')
Food.create(name:'柿', category:'果物')
Food.create(name:'栗', category:'果物')
Food.create(name:'ぶどう', category:'果物')
Food.create(name:'バナナ', category:'果物')
Food.create(name:'もも', category:'果物')
Food.create(name:'梨', category:'果物')

user1 = User.create(nickname:'テストユーザー1', email:'q1q1q1@q1.com', password:'q1q1q1', gender_id:1, birthday:'2000-01-01')
user2 = User.create(nickname:'テストユーザー2', email:'q2q2q2@q2.com', password:'q2q2q2', gender_id:2, birthday:'2000-01-01')
user3 = User.create(nickname:'テストユーザー3', email:'q3q3q3@q3.com', password:'q3q3q3', gender_id:3, birthday:'2000-01-01')

recipe = Recipe.new(cooking_name: 'ハンバーグ', how_to_cook: '作り方', genre_id: 2, user_id:user1.id)
recipe.recipes_foods.new(food_id: Food.find_by(name: '牛ひき肉').id)
recipe.recipes_foods.new(food_id: Food.find_by(name: 'たまねぎ').id)
file_path = Pathname.new(Rails.root.join("app/assets/images/recipes/ハンバーグ.jpeg"))
recipe.image.attach(io: File.open(file_path), filename: 'recipe.jpeg', content_type: 'image/jpeg')
recipe.save